Translation to en
BFI-Stiftung/BFI-Stiftung.github.io pull request #1
Opened 2022-02-11 09:26 UTC by KasprzMa

# What i did
- Added menu item for select language
- Added english version of index.html and imprint and privacy

2022-02-11 10:25 UTC, web-devil requested changes

2022-02-11 10:25 UTC, web-devil commented on css/styles.css
> +a{
das wäre jetzt für alle a tags
besser man nested das

`.languages-switcher a {}`

2022-02-11 10:25 UTC, web-devil commented on imprint-privacy_en.html
> +                <ul>
bitte vollständige navigation von index.html

2022-02-11 10:25 UTC, web-devil commented on imprint-privacy_en.html
> +            <h1>Imprint</h1>
AC Hinweis automatische Übersetzung bitte noch umsetzen

2022-02-11 10:25 UTC, web-devil commented on index.html
> -<html lang="en">
Der Diff ist hier komisch. Was genau hat sich verändert? (außer Language Switch)

2022-02-11 10:25 UTC, web-devil commented on index.html
> +                    <li><a href="index.html" language="german" class="active_de">DE</a>|<a href="index_en.html"
ist der Language Tag HTML5 konform?

2022-02-11 10:25 UTC, web-devil commented on index_en.html
> +                <strong>We offer young adults IT boot camps to work in
bootcamp zusammenschreiben

2022-02-11 10:25 UTC, web-devil commented on index_en.html
> +                <strong>We offer young adults IT boot camps to work in
Ich werde den Text später noch einmal Proofreaden (außerhalb dieser Code Review)

2022-02-15 10:49 UTC, KasprzMa commented on css/styles.css
> +a{
Zeilen für background:blue gelöscht, da nicht benötigt.
a{ kann meiner Meinung nach so bleiben. Es findet praktisch kein Konflikt statt und hat keinen Mehrwert.

2022-02-15 10:53 UTC, KasprzMa commented on imprint-privacy_en.html
> +                <ul>
Bitte näher erläutern. Entsprechende Zeilen sind gleich. Es kann von index in imprint und zurück navigiert werden. Mit Sprachauswahl

2022-02-15 10:55 UTC, KasprzMa commented on imprint-privacy_en.html
> +            <h1>Imprint</h1>
Der Text wurde manuell mit deepl übersetzt. Darauf verweisen oder eine automatische Übersetzung einbauen und dann darauf hinweise (nach Absprache mit Manuel)?

2022-02-15 10:58 UTC, KasprzMa commented on index.html
> -<html lang="en">
Nichts weiter. Kann ich aktuell nicht genau sagen.

2022-02-15 11:02 UTC, KasprzMa commented on index.html
> +                    <li><a href="index.html" language="german" class="active_de">DE</a>|<a href="index_en.html"
Wurde geändert.

2022-02-15 11:05 UTC, KasprzMa commented on index_en.html
> +                <strong>We offer young adults IT boot camps to work in
Wurde korrigiert

2022-02-16 06:41 UTC, web-devil approved these changes

2022-02-16 06:41 UTC, web-devil commented on imprint-privacy_en.html
> +            <h1>Imprint</h1>
Nur einen kleinen Satz hinzufügen.

2022-02-16 06:41 UTC, merged